# ===================================================================
# 1. APPLICATION & PROFILES
# ===================================================================
spring.application.name=fdw-analytics-engine
spring.profiles.active=local

# ===================================================================
# 2. SERVER & HTTPS CONFIGURATION
# ===================================================================
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=admin123
server.ssl.key-alias=analytics

# ===================================================================
# 3. DATABASE CONFIGURATION (PostgreSQL)
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/FinDataWarehouseDB
spring.datasource.username=python_dbuser
spring.datasource.password=th1s!SmyPy7onpW
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# 4. JPA / HIBERNATE CONFIGURATION
# ===================================================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

<<<<<<< HEAD
spring.profiles.active=local
spring.sql.init.mode=always
=======
# ===================================================================
# 5. CUSTOM SECURITY PROPERTIES
# ===================================================================
app.api.key=l`_Ggpsg[h8eGZZOPCK-;r(p1MQa+aCT

# ===================================================================
# 6. DEBUG
# ===================================================================
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
>>>>>>> feature/frontend
