spring.application.name=fdw-analytics-engine

spring.datasource.url=jdbc:postgresql://localhost:5432/FinDataWarehouseDB
spring.datasource.username=python_dbuser
spring.datasource.password=th1s!SmyPy7onpW
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate