# ===================================================================
# 1. APPLICATION & PROFILES
# ===================================================================
spring.application.name=fdw-analytics-engine

# ===================================================================
# 2. SERVER & HTTPS CONFIGURATION
# ===================================================================
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=admin123
server.ssl.key-alias=analytics

# ===================================================================
# 3. DATABASE CONFIGURATION (PostgreSQL)
# ===================================================================
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/FinDataWarehouseDB
spring.datasource.username=python_dbuser
spring.datasource.password=th1s!SmyPy7onpW
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# 4. JPA / HIBERNATE CONFIGURATION
# ===================================================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.profiles.active=local
spring.sql.init.mode=always

# SQL-Query in der Konsole
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# Zeigt die konkreten Parameterwerte (z. B. symbol = 'DAX')
# logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ===================================================================
# 5. API KEY
# ===================================================================
app.api.key=OZpAJ)C>2>EBWe9ee<R|f[%Rp"OucF31